# Generated by Django 4.2.3 on 2023-07-12 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('online', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('leader', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_led', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='groups_joined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
