# Generated by Django 4.2.3 on 2023-07-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('academic', 'Academics'), ('creative', 'Creativity'), ('sports', 'Sports and Fitness'), ('social', 'Social Causes'), ('technology', 'Technology and Innovation'), ('gaming', 'Gaming'), ('leadership', 'Leadership and Entrepreneurship'), ('health', 'Health and Wellness'), ('music', 'Music and Instruments'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
