# Generated by Django 4.2.3 on 2023-07-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0006_alter_group_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('Select Category', (('academic', 'Academics'), ('creative', 'Creativity'), ('sports', 'Sports and Fitness'), ('social', 'Social Causes'), ('technology', 'Technology and Innovation'), ('gaming', 'Gaming'), ('leadership', 'Leadership and Entrepreneurship'), ('health', 'Health and Wellness'), ('music', 'Music and Instruments'), ('other', 'Other')))], default='other', max_length=16),
        ),
    ]
