# Generated by Django 4.2.3 on 2023-07-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0009_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
