# Generated by Django 4.2.3 on 2023-07-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0010_alter_user_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school',
            new_name='highschool',
        ),
    ]
