# Generated by Django 4.2.3 on 2023-09-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0012_forum_remove_group_online_remove_user_highschool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profileimg',
            new_name='profile_img',
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_goal',
            field=models.TextField(blank=True),
        ),
    ]
