# Generated by Django 4.2.3 on 2023-09-25 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0015_rename_leader_group_admins_group_group_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='groups_led', to=settings.AUTH_USER_MODEL),
        ),
    ]
