# Generated by Django 4.2.3 on 2023-09-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0017_remove_forum_image_forum_forum_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='forum_attachment',
            field=models.FileField(blank=True, upload_to='forum_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='group_images/%Y/%m/%d/'),
        ),
    ]
