# Generated by Django 4.2.3 on 2023-10-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0022_alter_user_profile_img_alter_user_weekly_goal_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('Select Category', (('mindfulness', 'Motivation and Mindfulness '), ('mental', 'Mental Health'), ('substances', 'Substance Abuse'), ('behavioral', 'Behavioral Addiction')))], default='other', max_length=16),
        ),
    ]
