# Generated by Django 4.2.3 on 2023-10-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0024_affirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
