# Generated by Django 4.2.3 on 2023-10-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0025_user_isprivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isPrivate',
        ),
        migrations.AddField(
            model_name='user',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
