# Generated by Django 4.2.3 on 2023-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0026_remove_user_isprivate_user_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
