# Generated by Django 4.2.3 on 2023-10-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0028_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
