# Generated by Django 4.2.3 on 2023-10-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0030_alter_comment_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
