# Generated by Django 4.2.3 on 2023-10-30 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0031_alter_forum_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forum_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
