# Generated by Django 4.2.3 on 2023-11-01 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0032_comment_likes_forum_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal_created_on',
            field=models.DateField(default=datetime.date(2023, 10, 21)),
        ),
    ]
